#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Journey")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFamous_Place(Famous_Place instance);
    partial void UpdateFamous_Place(Famous_Place instance);
    partial void DeleteFamous_Place(Famous_Place instance);
    partial void InsertFood_Bev(Food_Bev instance);
    partial void UpdateFood_Bev(Food_Bev instance);
    partial void DeleteFood_Bev(Food_Bev instance);
    partial void InsertHospital_Clinic(Hospital_Clinic instance);
    partial void UpdateHospital_Clinic(Hospital_Clinic instance);
    partial void DeleteHospital_Clinic(Hospital_Clinic instance);
    partial void InsertHotel(Hotel instance);
    partial void UpdateHotel(Hotel instance);
    partial void DeleteHotel(Hotel instance);
    partial void InsertSouvenir_Shop(Souvenir_Shop instance);
    partial void UpdateSouvenir_Shop(Souvenir_Shop instance);
    partial void DeleteSouvenir_Shop(Souvenir_Shop instance);
    partial void InserttbVPimg(tbVPimg instance);
    partial void UpdatetbVPimg(tbVPimg instance);
    partial void DeletetbVPimg(tbVPimg instance);
    partial void InsertVehicle(Vehicle instance);
    partial void UpdateVehicle(Vehicle instance);
    partial void DeleteVehicle(Vehicle instance);
    partial void InsertVisit_Place(Visit_Place instance);
    partial void UpdateVisit_Place(Visit_Place instance);
    partial void DeleteVisit_Place(Visit_Place instance);
    partial void InserttbFBimg(tbFBimg instance);
    partial void UpdatetbFBimg(tbFBimg instance);
    partial void DeletetbFBimg(tbFBimg instance);
    partial void InserttbFPimg(tbFPimg instance);
    partial void UpdatetbFPimg(tbFPimg instance);
    partial void DeletetbFPimg(tbFPimg instance);
    partial void InserttbHCimg(tbHCimg instance);
    partial void UpdatetbHCimg(tbHCimg instance);
    partial void DeletetbHCimg(tbHCimg instance);
    partial void InserttbHotelimg(tbHotelimg instance);
    partial void UpdatetbHotelimg(tbHotelimg instance);
    partial void DeletetbHotelimg(tbHotelimg instance);
    partial void InserttbSSimg(tbSSimg instance);
    partial void UpdatetbSSimg(tbSSimg instance);
    partial void DeletetbSSimg(tbSSimg instance);
    partial void InserttbVimg(tbVimg instance);
    partial void UpdatetbVimg(tbVimg instance);
    partial void DeletetbVimg(tbVimg instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["JourneyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Famous_Place> Famous_Places
		{
			get
			{
				return this.GetTable<Famous_Place>();
			}
		}
		
		public System.Data.Linq.Table<Food_Bev> Food_Bevs
		{
			get
			{
				return this.GetTable<Food_Bev>();
			}
		}
		
		public System.Data.Linq.Table<Hospital_Clinic> Hospital_Clinics
		{
			get
			{
				return this.GetTable<Hospital_Clinic>();
			}
		}
		
		public System.Data.Linq.Table<Hotel> Hotels
		{
			get
			{
				return this.GetTable<Hotel>();
			}
		}
		
		public System.Data.Linq.Table<Souvenir_Shop> Souvenir_Shops
		{
			get
			{
				return this.GetTable<Souvenir_Shop>();
			}
		}
		
		public System.Data.Linq.Table<tbVPimg> tbVPimgs
		{
			get
			{
				return this.GetTable<tbVPimg>();
			}
		}
		
		public System.Data.Linq.Table<Vehicle> Vehicles
		{
			get
			{
				return this.GetTable<Vehicle>();
			}
		}
		
		public System.Data.Linq.Table<Visit_Place> Visit_Places
		{
			get
			{
				return this.GetTable<Visit_Place>();
			}
		}
		
		public System.Data.Linq.Table<tbFBimg> tbFBimgs
		{
			get
			{
				return this.GetTable<tbFBimg>();
			}
		}
		
		public System.Data.Linq.Table<tbFPimg> tbFPimgs
		{
			get
			{
				return this.GetTable<tbFPimg>();
			}
		}
		
		public System.Data.Linq.Table<tbHCimg> tbHCimgs
		{
			get
			{
				return this.GetTable<tbHCimg>();
			}
		}
		
		public System.Data.Linq.Table<tbHotelimg> tbHotelimgs
		{
			get
			{
				return this.GetTable<tbHotelimg>();
			}
		}
		
		public System.Data.Linq.Table<tbSSimg> tbSSimgs
		{
			get
			{
				return this.GetTable<tbSSimg>();
			}
		}
		
		public System.Data.Linq.Table<tbVimg> tbVimgs
		{
			get
			{
				return this.GetTable<tbVimg>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Famous_Place")]
	public partial class Famous_Place : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Famous_Place_ID;
		
		private string _Famous_Place_Name;
		
		private string _Famous_Place_Desc;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFamous_Place_IDChanging(string value);
    partial void OnFamous_Place_IDChanged();
    partial void OnFamous_Place_NameChanging(string value);
    partial void OnFamous_Place_NameChanged();
    partial void OnFamous_Place_DescChanging(string value);
    partial void OnFamous_Place_DescChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public Famous_Place()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Famous_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Famous_Place_ID
		{
			get
			{
				return this._Famous_Place_ID;
			}
			set
			{
				if ((this._Famous_Place_ID != value))
				{
					this.OnFamous_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Famous_Place_ID = value;
					this.SendPropertyChanged("Famous_Place_ID");
					this.OnFamous_Place_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Famous_Place_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Famous_Place_Name
		{
			get
			{
				return this._Famous_Place_Name;
			}
			set
			{
				if ((this._Famous_Place_Name != value))
				{
					this.OnFamous_Place_NameChanging(value);
					this.SendPropertyChanging();
					this._Famous_Place_Name = value;
					this.SendPropertyChanged("Famous_Place_Name");
					this.OnFamous_Place_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Famous_Place_Desc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Famous_Place_Desc
		{
			get
			{
				return this._Famous_Place_Desc;
			}
			set
			{
				if ((this._Famous_Place_Desc != value))
				{
					this.OnFamous_Place_DescChanging(value);
					this.SendPropertyChanging();
					this._Famous_Place_Desc = value;
					this.SendPropertyChanged("Famous_Place_Desc");
					this.OnFamous_Place_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Food_Bev")]
	public partial class Food_Bev : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Food_Bev_ID;
		
		private string _Food_Bev_Name;
		
		private string _Food_Bev_Desc;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFood_Bev_IDChanging(string value);
    partial void OnFood_Bev_IDChanged();
    partial void OnFood_Bev_NameChanging(string value);
    partial void OnFood_Bev_NameChanged();
    partial void OnFood_Bev_DescChanging(string value);
    partial void OnFood_Bev_DescChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public Food_Bev()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Bev_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Food_Bev_ID
		{
			get
			{
				return this._Food_Bev_ID;
			}
			set
			{
				if ((this._Food_Bev_ID != value))
				{
					this.OnFood_Bev_IDChanging(value);
					this.SendPropertyChanging();
					this._Food_Bev_ID = value;
					this.SendPropertyChanged("Food_Bev_ID");
					this.OnFood_Bev_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Bev_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Food_Bev_Name
		{
			get
			{
				return this._Food_Bev_Name;
			}
			set
			{
				if ((this._Food_Bev_Name != value))
				{
					this.OnFood_Bev_NameChanging(value);
					this.SendPropertyChanging();
					this._Food_Bev_Name = value;
					this.SendPropertyChanged("Food_Bev_Name");
					this.OnFood_Bev_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Bev_Desc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Food_Bev_Desc
		{
			get
			{
				return this._Food_Bev_Desc;
			}
			set
			{
				if ((this._Food_Bev_Desc != value))
				{
					this.OnFood_Bev_DescChanging(value);
					this.SendPropertyChanging();
					this._Food_Bev_Desc = value;
					this.SendPropertyChanged("Food_Bev_Desc");
					this.OnFood_Bev_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hospital_Clinic")]
	public partial class Hospital_Clinic : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Hospital_Clinic_ID;
		
		private string _Hospital_Clinic_Name;
		
		private string _Hospital_Clinic_Desc;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHospital_Clinic_IDChanging(string value);
    partial void OnHospital_Clinic_IDChanged();
    partial void OnHospital_Clinic_NameChanging(string value);
    partial void OnHospital_Clinic_NameChanged();
    partial void OnHospital_Clinic_DescChanging(string value);
    partial void OnHospital_Clinic_DescChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public Hospital_Clinic()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Clinic_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Hospital_Clinic_ID
		{
			get
			{
				return this._Hospital_Clinic_ID;
			}
			set
			{
				if ((this._Hospital_Clinic_ID != value))
				{
					this.OnHospital_Clinic_IDChanging(value);
					this.SendPropertyChanging();
					this._Hospital_Clinic_ID = value;
					this.SendPropertyChanged("Hospital_Clinic_ID");
					this.OnHospital_Clinic_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Clinic_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Hospital_Clinic_Name
		{
			get
			{
				return this._Hospital_Clinic_Name;
			}
			set
			{
				if ((this._Hospital_Clinic_Name != value))
				{
					this.OnHospital_Clinic_NameChanging(value);
					this.SendPropertyChanging();
					this._Hospital_Clinic_Name = value;
					this.SendPropertyChanged("Hospital_Clinic_Name");
					this.OnHospital_Clinic_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Clinic_Desc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Hospital_Clinic_Desc
		{
			get
			{
				return this._Hospital_Clinic_Desc;
			}
			set
			{
				if ((this._Hospital_Clinic_Desc != value))
				{
					this.OnHospital_Clinic_DescChanging(value);
					this.SendPropertyChanging();
					this._Hospital_Clinic_Desc = value;
					this.SendPropertyChanged("Hospital_Clinic_Desc");
					this.OnHospital_Clinic_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hotel")]
	public partial class Hotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Hotel_ID;
		
		private string _Hotel_Name;
		
		private string _Hotel_Desc;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHotel_IDChanging(string value);
    partial void OnHotel_IDChanged();
    partial void OnHotel_NameChanging(string value);
    partial void OnHotel_NameChanged();
    partial void OnHotel_DescChanging(string value);
    partial void OnHotel_DescChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public Hotel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Hotel_ID
		{
			get
			{
				return this._Hotel_ID;
			}
			set
			{
				if ((this._Hotel_ID != value))
				{
					this.OnHotel_IDChanging(value);
					this.SendPropertyChanging();
					this._Hotel_ID = value;
					this.SendPropertyChanged("Hotel_ID");
					this.OnHotel_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Hotel_Name
		{
			get
			{
				return this._Hotel_Name;
			}
			set
			{
				if ((this._Hotel_Name != value))
				{
					this.OnHotel_NameChanging(value);
					this.SendPropertyChanging();
					this._Hotel_Name = value;
					this.SendPropertyChanged("Hotel_Name");
					this.OnHotel_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel_Desc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Hotel_Desc
		{
			get
			{
				return this._Hotel_Desc;
			}
			set
			{
				if ((this._Hotel_Desc != value))
				{
					this.OnHotel_DescChanging(value);
					this.SendPropertyChanging();
					this._Hotel_Desc = value;
					this.SendPropertyChanged("Hotel_Desc");
					this.OnHotel_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Souvenir_Shop")]
	public partial class Souvenir_Shop : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Souvenir_Shop_ID;
		
		private string _Souvenir_Shop_Name;
		
		private string _Souvenir_Shop_Desc;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSouvenir_Shop_IDChanging(string value);
    partial void OnSouvenir_Shop_IDChanged();
    partial void OnSouvenir_Shop_NameChanging(string value);
    partial void OnSouvenir_Shop_NameChanged();
    partial void OnSouvenir_Shop_DescChanging(string value);
    partial void OnSouvenir_Shop_DescChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public Souvenir_Shop()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Souvenir_Shop_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Souvenir_Shop_ID
		{
			get
			{
				return this._Souvenir_Shop_ID;
			}
			set
			{
				if ((this._Souvenir_Shop_ID != value))
				{
					this.OnSouvenir_Shop_IDChanging(value);
					this.SendPropertyChanging();
					this._Souvenir_Shop_ID = value;
					this.SendPropertyChanged("Souvenir_Shop_ID");
					this.OnSouvenir_Shop_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Souvenir_Shop_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Souvenir_Shop_Name
		{
			get
			{
				return this._Souvenir_Shop_Name;
			}
			set
			{
				if ((this._Souvenir_Shop_Name != value))
				{
					this.OnSouvenir_Shop_NameChanging(value);
					this.SendPropertyChanging();
					this._Souvenir_Shop_Name = value;
					this.SendPropertyChanged("Souvenir_Shop_Name");
					this.OnSouvenir_Shop_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Souvenir_Shop_Desc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Souvenir_Shop_Desc
		{
			get
			{
				return this._Souvenir_Shop_Desc;
			}
			set
			{
				if ((this._Souvenir_Shop_Desc != value))
				{
					this.OnSouvenir_Shop_DescChanging(value);
					this.SendPropertyChanging();
					this._Souvenir_Shop_Desc = value;
					this.SendPropertyChanged("Souvenir_Shop_Desc");
					this.OnSouvenir_Shop_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbVPimg")]
	public partial class tbVPimg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Visit_Place_Image_ID;
		
		private string _Visit_Place_ID;
		
		private System.Data.Linq.Binary _image;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVisit_Place_Image_IDChanging(string value);
    partial void OnVisit_Place_Image_IDChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    #endregion
		
		public tbVPimg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_Image_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Visit_Place_Image_ID
		{
			get
			{
				return this._Visit_Place_Image_ID;
			}
			set
			{
				if ((this._Visit_Place_Image_ID != value))
				{
					this.OnVisit_Place_Image_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_Image_ID = value;
					this.SendPropertyChanged("Visit_Place_Image_ID");
					this.OnVisit_Place_Image_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vehicle")]
	public partial class Vehicle : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Vehicle_ID;
		
		private string _Vehicle_Name;
		
		private string _Vehicle_Desc;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVehicle_IDChanging(string value);
    partial void OnVehicle_IDChanged();
    partial void OnVehicle_NameChanging(string value);
    partial void OnVehicle_NameChanged();
    partial void OnVehicle_DescChanging(string value);
    partial void OnVehicle_DescChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public Vehicle()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehicle_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Vehicle_ID
		{
			get
			{
				return this._Vehicle_ID;
			}
			set
			{
				if ((this._Vehicle_ID != value))
				{
					this.OnVehicle_IDChanging(value);
					this.SendPropertyChanging();
					this._Vehicle_ID = value;
					this.SendPropertyChanged("Vehicle_ID");
					this.OnVehicle_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehicle_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Vehicle_Name
		{
			get
			{
				return this._Vehicle_Name;
			}
			set
			{
				if ((this._Vehicle_Name != value))
				{
					this.OnVehicle_NameChanging(value);
					this.SendPropertyChanging();
					this._Vehicle_Name = value;
					this.SendPropertyChanged("Vehicle_Name");
					this.OnVehicle_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehicle_Desc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Vehicle_Desc
		{
			get
			{
				return this._Vehicle_Desc;
			}
			set
			{
				if ((this._Vehicle_Desc != value))
				{
					this.OnVehicle_DescChanging(value);
					this.SendPropertyChanging();
					this._Vehicle_Desc = value;
					this.SendPropertyChanged("Vehicle_Desc");
					this.OnVehicle_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visit_Place")]
	public partial class Visit_Place : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Visit_Place_ID;
		
		private string _Visit_Place_Name;
		
		private string _Visit_Place_Desc;
		
		private System.DateTime _CreatedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    partial void OnVisit_Place_NameChanging(string value);
    partial void OnVisit_Place_NameChanged();
    partial void OnVisit_Place_DescChanging(string value);
    partial void OnVisit_Place_DescChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    #endregion
		
		public Visit_Place()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Visit_Place_Name
		{
			get
			{
				return this._Visit_Place_Name;
			}
			set
			{
				if ((this._Visit_Place_Name != value))
				{
					this.OnVisit_Place_NameChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_Name = value;
					this.SendPropertyChanged("Visit_Place_Name");
					this.OnVisit_Place_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_Desc", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Visit_Place_Desc
		{
			get
			{
				return this._Visit_Place_Desc;
			}
			set
			{
				if ((this._Visit_Place_Desc != value))
				{
					this.OnVisit_Place_DescChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_Desc = value;
					this.SendPropertyChanged("Visit_Place_Desc");
					this.OnVisit_Place_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="Date NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbFBimg")]
	public partial class tbFBimg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Food_Bev_Image_ID;
		
		private System.Data.Linq.Binary _image;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFood_Bev_Image_IDChanging(string value);
    partial void OnFood_Bev_Image_IDChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public tbFBimg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Bev_Image_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Food_Bev_Image_ID
		{
			get
			{
				return this._Food_Bev_Image_ID;
			}
			set
			{
				if ((this._Food_Bev_Image_ID != value))
				{
					this.OnFood_Bev_Image_IDChanging(value);
					this.SendPropertyChanging();
					this._Food_Bev_Image_ID = value;
					this.SendPropertyChanged("Food_Bev_Image_ID");
					this.OnFood_Bev_Image_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbFPimg")]
	public partial class tbFPimg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Famous_Place_Image_ID;
		
		private System.Data.Linq.Binary _image;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFamous_Place_Image_IDChanging(string value);
    partial void OnFamous_Place_Image_IDChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public tbFPimg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Famous_Place_Image_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Famous_Place_Image_ID
		{
			get
			{
				return this._Famous_Place_Image_ID;
			}
			set
			{
				if ((this._Famous_Place_Image_ID != value))
				{
					this.OnFamous_Place_Image_IDChanging(value);
					this.SendPropertyChanging();
					this._Famous_Place_Image_ID = value;
					this.SendPropertyChanged("Famous_Place_Image_ID");
					this.OnFamous_Place_Image_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHCimg")]
	public partial class tbHCimg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Hospital_Clinic_Image_ID;
		
		private System.Data.Linq.Binary _image;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHospital_Clinic_Image_IDChanging(string value);
    partial void OnHospital_Clinic_Image_IDChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public tbHCimg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hospital_Clinic_Image_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Hospital_Clinic_Image_ID
		{
			get
			{
				return this._Hospital_Clinic_Image_ID;
			}
			set
			{
				if ((this._Hospital_Clinic_Image_ID != value))
				{
					this.OnHospital_Clinic_Image_IDChanging(value);
					this.SendPropertyChanging();
					this._Hospital_Clinic_Image_ID = value;
					this.SendPropertyChanged("Hospital_Clinic_Image_ID");
					this.OnHospital_Clinic_Image_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbHotelimg")]
	public partial class tbHotelimg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Hotel_Image_ID;
		
		private System.Data.Linq.Binary _image;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHotel_Image_IDChanging(string value);
    partial void OnHotel_Image_IDChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public tbHotelimg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hotel_Image_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Hotel_Image_ID
		{
			get
			{
				return this._Hotel_Image_ID;
			}
			set
			{
				if ((this._Hotel_Image_ID != value))
				{
					this.OnHotel_Image_IDChanging(value);
					this.SendPropertyChanging();
					this._Hotel_Image_ID = value;
					this.SendPropertyChanged("Hotel_Image_ID");
					this.OnHotel_Image_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSSimg")]
	public partial class tbSSimg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Souvenir_Shop_Image_ID;
		
		private System.Data.Linq.Binary _image;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSouvenir_Shop_Image_IDChanging(string value);
    partial void OnSouvenir_Shop_Image_IDChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public tbSSimg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Souvenir_Shop_Image_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Souvenir_Shop_Image_ID
		{
			get
			{
				return this._Souvenir_Shop_Image_ID;
			}
			set
			{
				if ((this._Souvenir_Shop_Image_ID != value))
				{
					this.OnSouvenir_Shop_Image_IDChanging(value);
					this.SendPropertyChanging();
					this._Souvenir_Shop_Image_ID = value;
					this.SendPropertyChanged("Souvenir_Shop_Image_ID");
					this.OnSouvenir_Shop_Image_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbVimg")]
	public partial class tbVimg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Vehicle_Image_ID;
		
		private System.Data.Linq.Binary _image;
		
		private string _Visit_Place_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVehicle_Image_IDChanging(string value);
    partial void OnVehicle_Image_IDChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnVisit_Place_IDChanging(string value);
    partial void OnVisit_Place_IDChanged();
    #endregion
		
		public tbVimg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehicle_Image_ID", DbType="Char(36) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Vehicle_Image_ID
		{
			get
			{
				return this._Vehicle_Image_ID;
			}
			set
			{
				if ((this._Vehicle_Image_ID != value))
				{
					this.OnVehicle_Image_IDChanging(value);
					this.SendPropertyChanging();
					this._Vehicle_Image_ID = value;
					this.SendPropertyChanged("Vehicle_Image_ID");
					this.OnVehicle_Image_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visit_Place_ID", DbType="Char(36) NOT NULL", CanBeNull=false)]
		public string Visit_Place_ID
		{
			get
			{
				return this._Visit_Place_ID;
			}
			set
			{
				if ((this._Visit_Place_ID != value))
				{
					this.OnVisit_Place_IDChanging(value);
					this.SendPropertyChanging();
					this._Visit_Place_ID = value;
					this.SendPropertyChanged("Visit_Place_ID");
					this.OnVisit_Place_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
